name: worldborder
version: '1.0-SNAPSHOT'
main: site.frii.worldborder.WorldborderManager
api-version: '1.20'

commands:
  amount:
    description: Sets the world border expand amount (/amount 0.5)
    usage: /amount <double>
    permission: wb.set

  sync:
    description: Syncs the world border size
    usage: /sync
    permission: wb.sync