name: worldborder
version: '1.1'
main: site.frii.worldborder.WorldborderManager
api-version: '1.13'
author: Onni Nevala

commands:
  multiplier:
    description: Sets how many blocks the world border expands per advancement
    usage: /multiplier <double>
    permission: wb.set
    aliases:
      - amount

  sync:
    description: Syncs the world border size with the multiplier and advancement amount
    usage: /sync
    permission: wb.sync

  advancements:
    description: Get the amount of advancements unlocked
    usage: /advancements
    permission: wb.advancement
    aliases:
      - achievements
      - size

  settings:
    description: Change a setting. A list of settings can be viewed with '/settings'
    usage: /settings <setting> <mode>
    permission: wb.settings
    aliases:
      - setting

